spin_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A simple URL shortener built with Spin."
name = "url-shortener"
trigger = { type = "http", base = "/" }
version = "1.0.0"

[[component]]
id = "shortener"
source = "target/wasm32-wasi/release/url_shortener.wasm"
files = [ "router.toml" ]
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
